[정병휘] 로그인(unit test x)
wecode-bootcamp-korea/33-2nd-ourTrip-backend pull request #3
Opened 2022-06-10 04:12 UTC by ByeonghwiJeong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. KakaoSignView : 인가코드받기위한 API Redirect(+ 로그인)
2. KakaoLoginView
   - 인가코드이용해서 토큰 받기
   - 토큰을 이용해서 kakao_id얻은후 DB의 kakao_id값 비교
      - 회원가입&로그인  
      - 로그인
   - kakao_id을 이용해서 토큰 응답

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-06-10 05:07 UTC, bigfanoftim requested changes
병휘님 해당 코드 실행이 되나요?

2022-06-10 07:15 UTC, ByeonghwiJeong commented
네 프론트와 직접 통신은 안했고
제 노트북으로 localhost:8000/users/kakao로 접속하면 카카오 로그인 창열리고
로그인 완료하면 아래 사진과 같이 kakao_id로 만든 token과 DB에도 반영이됩니다.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/95831345/173011091-766dbe06-138d-4e20-afb7-c8a8ba843806.png">


<img width="625" alt="image" src="https://user-images.githubusercontent.com/95831345/173010646-168b7242-520f-4649-9142-a1e6555bd900.png">

2022-06-10 08:01 UTC, bigfanoftim requested changes

2022-06-10 08:01 UTC, bigfanoftim commented on users/views.py
> +        }
<img width="838" alt="image" src="https://user-images.githubusercontent.com/62135254/173017081-330a298d-f3cd-4ca0-ae6b-05484bbda4e0.png">
키값 정확히 맞춰주세요~

2022-06-13 00:52 UTC, bigfanoftim approved these changes
LGTM 👍

2022-06-13 00:52 UTC, merged